#!/bin/bash
#SBATCH --job-name=animate_lcao
#SBATCH --output=animate_%j.out
#SBATCH -p RM-shared
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH -t 00:05:00

module purge
module load anaconda3/2022.10
module load ffmpeg

python3 /ocean/projects/mat250017p/desantos/projects/Animate/animateLcao.py $1

#python3 /ocean/projects/mat250017p/desantos/projects/Animate/hist2xyz.py
#python3 /ocean/projects/mat250017p/desantos/projects/Animate/animatexyz.py