#!/bin/bash
#SBATCH --job-name=run_fix
#SBATCH --output=animate_%j.out
#SBATCH -p RM-shared
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH -t 00:05:00

module purge
module load anaconda3/2022.10
module load ffmpeg

#python3 /ocean/projects/mat250017p/desantos/projects/NEBCrosslink/run_fix.py > efinal_fixed.txt

#python3 /ocean/projects/mat250017p/desantos/projects/NEBCrosslink/generate_sanity.py

#python3 /ocean/projects/mat250017p/desantos/projects/NEBCrosslink/fix_neb_centered.py

python3 /ocean/projects/mat250017p/desantos/projects/NEBCrosslink/aes_reorder.py
