#!/bin/bash
#SBATCH --job-name=NEB2XYZ_lcao
#SBATCH --output=NEB2XYZ_%j.out
#SBATCH -p RM-shared
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH -t 00:05:00

module purge
module load anaconda3/2022.10
module load ffmpeg

cd /ocean/projects/mat250017p/desantos/projects/NEBCrosslinkWork/NEBTestIDPP/LPStart

python3 /ocean/projects/mat250017p/desantos/scripts/NEBimages2xyz.py /ocean/projects/mat250017p/desantos/projects/NEBCrosslinkWork/NEBTestIDPP/LPStart/lcao.neb_geom "LPstart"